---
# Initial rollout is needed to configure dependencies
- include_vars: repositories.yml

  # Install Dependencies
- include: spark.yml

- name: Installing deploy key
  copy: content={{ ml_key }}
        dest=/home/denis/.ssh/{{ ml_key_name }}
        mode=0600
        owner=denis
        group=denis

- name: Cloning ML repository
  git: repo={{ ml_repository_url }}
       dest={{ ml_clone_dest }}
       clone=yes
       version={{ ml_branch }}
       accept_hostkey=yes
       key_file=/home/denis/.ssh/{{ ml_key_name }}
  when: deploy_ml == true

