---
# Sets up bcache for raid

- name: Adding bcache-tools ppa
  copy: src=bcache-tools.list 
        dest=/etc/apt/sources.list.d/bcache-tools.list

- name: Adding repository key
  command: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4BBE1367"

- name: Installing bcache-tools
  apt: name=bcache-tools
       update_cache=yes
       state=latest

- name: Wiping cache device
  command: "wipefs {{ bcache_cache }}"

- name: Wiping cache device af
  command: "wipefs -af {{ bcache_cache }}"

- name: Wiping backing device
  command: "wipefs {{ bcache_backing }}"

- name: Wiping backing device af
  command: "wipefs -af {{ bcache_backing }}"

- name: Creating bcache device
  command: "make-bcache --wipe-bcache -B {{ bcache_backing }} --block 4k --bucket 2M -C {{ bcache_cache }}"

- name: Registering caching device
  shell: echo {{ bcache_cache | quote }} > /sys/fs/bcache/register_quiet
  ignore_errors: true

- name: Registering backing device
  shell: echo {{ bcache_backing | quote }} > /sys/fs/bcache/register_quiet
  ignore_errors: true

- name: FUCK YOU BCACHE
  shell: echo $(bcache-super-show {{ bcache_cache | quote }} | grep cset.uuid | sed -e 's/^cset.uuid\s\s//') > /home/denis/bcache

- name: Attaching cache device
  shell: echo $(bcache-super-show {{ bcache_cache | quote }} | grep cset.uuid | sed -e 's/^cset.uuid\s\s//') > /sys/block/bcache0/bcache/attach

- name: Setting cache mode
  shell: echo writeback > /sys/block/bcache0/bcache/cache_mode

- name: Configuring boot modules
  copy: src=modules
        dest=/etc/modules

- name: Configuring bcache
  copy: src=bcache.conf
        dest=/etc/tmpfiles.d/bcache.conf

