---
# Deploy ETL + ML server

- name: Building ETL/ML Host
  hosts: etl-servers
  remote_user: denis
  sudo: yes

  roles:
    - etl

- name: Deploying Containers
  hosts: containers
  remote_user: denis
  sudo: yes
  
  roles:
    - etl
    - deploy

