---
# Deploy ETL + ML server

- name: Configuring host
  hosts: dtfm-host
  remote_user: denis
  become: yes
  roles: [partitions, lxc]

- name: Building ETL Container
  hosts: [etl-clx01,etl-clx02]
  remote_user: root
  roles: [base, etl]

- name: Bulding ML Containers
  hosts: ml-clx01
  remote_user: root
  roles: [base, ml]

