---
# Deploy ETL + ML server

- name: Deploying host
  hosts: etl-servers
  remote_user: denis
  sudo: yes

  roles:
    - etl

- name: Deploying ETL development containers
  hosts: etl-dlxc
  remote_user: denis
  sudo: yes
  set_fact:
    deploy_etl: true
    etl_branch: "development"
  
  roles:
    - etl

- name: Deploying ETL production containers
  hosts: etl-plxc
  remote_user: denis
  sudo: yes
  set_fact:
    deploy_etl: true
    etl_branch: "master"
  
  roles:
    - etl

- name: Deploying ML development containers
  hosts: ml-dlxc
  remote_user: denis
  sudo: yes
  set_fact:
    deploy_ml: true
    ml_branch: "development"
  
  roles:
    - etl

- name: Deploying ML production containers
  hosts: ml-plxc
  remote_user: denis
  sudo: yes
  set_fact:
    deploy_ml: true
    ml_branch: "master"
  
  roles:
    - etl

