---
# Deploy ETL + ML server

- name: Building ETL Container
  hosts:
    - etl-plxc
    - etl-dlxc
  remote_user: denis
  sudo: yes

  roles:
    - etl

- name: Deploying to containers
  hosts: containers
  remote_user: denis
  sudo: yes
  
  roles:
    - deploy

