---

- name: Finalising servers
  hosts: [webserver-gateway, webserver-nodes]
  remote_user: denis
  become: true
  vars:
    root_pw: "{{host_root_pw}}"
    denis_pw: "{{host_denis_pw}}"
  roles: [finalise]
