---

#~ - name: Finalising servers
  #~ hosts: [webserver-gateway, webserver-nodes, dtfm-host, cluster-host, production-cluster]
  #~ remote_user: denis
  #~ become: true
  #~ vars:
    #~ root_pw: "{{host_root_pw}}"
    #~ additional_users: "{{host_users}}"
  #~ roles: [finalise]

- name: Finalising containers
  hosts: [nexus]
  remote_user: denis
  become: true
  vars:
    root_pw: "{{container_root_pw}}"
    additional_users: "{{container_users}}"
  roles: [finalise]
