---

- name: Finalising servers
  hosts: [webserver-gateway, webserver-nodes, dtfm-host, cluster-host]
  remote_user: denis
  become: true
  vars:
    root_pw: "{{host_root_pw}}"
    denis_pw: "{{host_denis_pw}}"
  roles: [finalise]

- name: Finalising containers
  hosts: [dtfm-containers, graph-manager-containers]
  remote_user: denis
  become: true
  vars:
    root_pw: "{{container_root_pw}}"
    denis_pw: "{{container_root_pw}}"
  roles: [finalise]
