---
# Test all roles

#- name: Test network ancillary setup
  #hosts: localvms
  #remote_user: denis
  #sudo: yes
  #
  #roles:
  #  - network-ancillary

- name: Testing raid setup
  hosts: localvms
  remote_user: denis
  sudo: yes
  roles:
    - webserver

