---
# Test all roles

#- name: Test network ancillary setup
  #hosts: localvms
  #remote_user: denis
  #sudo: yes
  #
  #roles:
  #  - network-ancillary

- name: LXC setup
  hosts: localvms
  remote_user: denis
  sudo: yes
  roles:
    - lxc

- name: Deploying ETL
  hosts: localvms
  remote_user: denis
  sudo: yes
  roles:
    - etl
    - deploy

