---

- name: Deploying gateway servers
  hosts: webserver-gateway
  remote_user: denis
  become: true
  roles: [partitions, webserver]

- name: Deploying node servers
  hosts: webserver-nodes
  remote_user: denis
  become: true
  roles: [webserver]
