---

- name: Configuring gateway hosts
  hosts: [webserver-gateway-host, webserver-node-hosts]
  remote_user: denis
  become: true
  roles: [partitions, lxc]

- name: Deploying Containers
  hosts: [db-containers, nginx-containers, tomcat-containers]
  remote_user: root
  roles: [base]

- name: Configuring DB containers
  hosts: [db-containers]
  remote_user: denis
  become: true
  roles: [database]

- name: Configuring Gateway containers
  hosts: [nginx-containers]
  remote_user: denis
  become: true
  roles: [nginx]

- name: Configuring node webserver containers
  hosts: [tomcat-containers]
  remote_user: denis
  become: true
  roles: [webserver]
