---

- name: Configuring /etc/hosts
  lineinfile: dest=/etc/hosts
              state=present
              line=127.0.0.1	{{inventory_hostname}}.internal.mindmaps.io	{{inventory_hostname}}

- name: Configuring hostname
  hostname: name={{inventory_hostname_short}}

