---
# Finalise server details - host & container passwords
- name: Setting root password
  user: name=root
        password={{ root_pw }}
        update_password=always

- name: Setting user password
  user: name={{item.name}}
        password={{item.pass}}
        update_password=always
  with_items:
    - "{{additional_users}}"

