---
# host & container passwords

- name: Setting root password
  user: name=root
        password={{ root_pw }}
        update_password=always

- name: Adding user groups
  group: name={{item.name}}
         state=present
         system=yes
  with_items:
    - "{{additional_users}}"

- name: Setting user password
  user: name={{item.name}}
        password={{item.pass}}
        update_password=always
        group={{item.name}}
        groups={{item.groups}}
        system=yes
        state=present
  with_items:
    - "{{additional_users}}"

- name: Adding ssh access
  authorized_key: user={{item.name}}
                  key={{item.key}}
                  state=present
  with_items:
    - "{{additional_users}}"

