---
# configure etherenet bridge for LXD

- name: Installing bridge utils
  apt: name=bridge-utils update_cache=no state=present

- name: Creating ethernet bridge for LXD
  command: brctl addbr lxdbr0
  ignore_errors: yes

- name: Bringing bridge up
  command: ip link set up dev lxdbr0

- name: Adding ethernet port to bridge
  command: brctl addif lxdbr0 eth0
  ignore_errors: yes

- name: Creating persistent configuration
  blockinfile:
    dest: /etc/network/interfaces
    insertafter: "# LXC bridge interfaces"
    state: present
    block: |
      auto lxdbr0
      iface lxdbr0 inet dhcp
        bridge_ports eth0
        bridge_fd 0
        bridge_maxwait 0 

