---

- name: restart docker
  service: name=docker state=restarted

- name: enable etcd
  service: name=etcd enabled=yes

- name: restart etcd
  service: name=etcd state=restarted

- name: enable kube-master
  service: name={{item}} enabled=yes
  with_items:
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"

- name: enable kube-minion
  service: name={{item}} enabled=yes
  with_items:
    - "kubelet"
    - "kube-proxy"

