---
# Configure virtual networks for containers

- name: Configuring host interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces

- name: Configuring host forwarding
  copy: src=sysctl.conf dest=/etc/sysctl.conf

- name: Updating iptables
  template: src=iptables.j2 dest=/etc/iptables/rules.v4
  notify: apply iptables

- name: Copying network restart script
  copy: src=network-restart.sh
        dest=/etc/network/ansible-restart.sh
        owner=root
        mode=0755
  notify: restart network
