---

- name: restart rpcbind
  service: name=rpcbind state=restarted

- name: restart nfs-kernel-server
  service: name=nfs-kernel-server state=restarted

- name: restart nginx
  service: name=nginx state=restarted

