---
# Set up network ancillary server

- name: Installing BIND9
  apt: name=bind9
       update_cache=yes
       state=latest

- name: Configuring BIND9
  copy: src={{ item  }} dest=/etc/bind9/
  with_items: 
      - "{{ bind9_files }}"
  notify: restart bind9

- name: Removing previous install
  command: "{{ item }}"
  with_items:
      - "rm /opt/nexus"
      - "rm -rf /opt/{{ nexus_version }}"
      - "rm -rf /opt/sonatype-work"
      - "rm -rf /srv/sonatype-work"
  ignore_errors: yes

- name: Installing Nexus
  unarchive: src={{ nexus_download_url }}
             dest=/opt/
             copy=yes

- name: Setting up work directory
  command: "{{ item }}"
  with_items:
      - "mv /opt/sonatype-work /srv/"
      - "ln -s /opt/{{ nexus_version }} /opt/nexus"

- name: Configuring Nexus
  copy: src=nexus.properties dest=/opt/nexus/conf/

- name: Creating nexus user group
  group: name=nexus
         system=yes
         state=present

- name: Creating nexus user
  user: name=nexus
        group=nexus
        shell=/bin/false
        system=yes
        state=present

- name: Copying init script
  copy: src=nexus 
        dest=/etc/init.d/
        mode=0755
  notify: start nexus

