---
# Install etcd

- name: Adding etcd group
  group: name=etcd system=yes state=present

- name: Adding etcd user
  user: name=etcd group=etcd shell=/bin/false home=/dev/null system=yes state=present

- name: Creating directories
  file: path={{item}} state=directory owner=etcd group=etcd
  with_items:
    - "{{etcd_extract_path}}"
    - "{{etcd_conf_path}}"
    - "{{etcd_data_path}}"

- name: Downloading etcd
  unarchive: src={{etcd_download_url}}
             dest={{etcd_extract_path}}
             copy=no

- name: Installing binaries
  command: cp {{etcd_extracted_path}}/{{item}} /usr/local/bin/
  with_items:
    - "etcd"
    - "etcdctl"

- name: Creating config
  template: src=etcd.j2 dest={{etcd_conf_path}}/etcd.conf owner=etcd group=etcd
  notify: restart etcd

- name: Copying systemd service
  copy: src=etcd.service dest=/etc/systemd/system
  notify:
    - enable etcd
    - reload systemd
    - restart etcd

