---

- include: docker.yml

- name: Adding kube group
  group: name=kube system=yes state=present

- name: Adding kube user
  user: name=kube group=kube shell=/bin/false home=/dev/null system=yes state=present

- name: Creating directories
  file: path={{item}} state=directory owner=kube group=kube
  with_items:
    - "{{kubernetes_extract_path}}"
    - "{{kube_conf_path}}"

- name: Downloading Kubernetes
  unarchive: src={{kubernetes_download_url}} dest={{kubernetes_extract_path}} copy=no owner=kube group=kube

- name: Extracting server binaries
  command: tar zxvf {{kubernetes_extract_path}}/kubernetes/server/kubernetes-server-linux-amd64.tar.gz
           chdir={{kubernetes_extract_path}}

- include: etcd.yml
  when: kube_master is defined and kube_master == true
  
- include: kubernetes-master.yml
  when: kube_master is defined and kube_master == true

- include: kubernetes-minion.yml
  when: kube_master is not defined or kube_master == false

