---
# Add non-root users here
- include_vars: users.yml

- name: Adding user groups
  group: name={{item.name}}
         state=present
         system=yes
  with_items:
    - "{{srv_users}}"

- name: Adding users
  user: name={{item.name}}
        password={{item.password}}
        update_password=on_create
        state=present
        group={{item.name}}
        groups="sudo"
        system=yes
  with_items:
    - "{{srv_users}}"

- name: Ensuring ssh is allowed
  authorized_key: user={{item.name}} 
                  key={{item.key}} 
                  state=present
  with_items:
    - "{{srv_users}}"


