---
# Configure NFS server

- name: Installing NFS dependencies
  apt: name={{item}} state=present
  with_items:
    - "nfs-kernel-server"
    - "rpcbind"
    - "nfs-common"

- name: Configuring hosts.deny
  copy: src=hosts.deny
        dest=/etc/hosts.deny
        owner=root
        group=root

- name: Configuring hosts.allow
  template: src=hosts.allow.j2
            dest=/etc/hosts.allow
            owner=root
            group=root
  notify: restart rpcbind

- name: Configuring nfs-common
  copy: src=nfs-common
        dest=/etc/default/nfs-common

- name: Configuring idmapd
  copy: src=idmapd.conf
        dest=/etc/idmapd.conf

- name: Configuring exports
  template: src=exports.j2
            dest=/etc/exports
  notify: restart nfs-kernel-server

