---
# Install and configure tomcat8

- name: Installing Tomcat8
  apt: name=tomcat8 update_cache=yes state=latest

- name: Copying Tomcat configuration files
  copy: src={{item.src}} dest={{item.dest}} owner=root group=root
  with_items:
    - {src: "ROOT.xml", dest: "/etc/tomcat8/Catalina/localhost/ROOT.xml"}
    - {src: "setenv.sh", dest: "/usr/share/tomcat8/bin/setenv.sh"}
    - {src: "tomcat8", dest: "/etc/default/tomcat8"}
  notify: restart tomcat

- name: Creating deployment base directories
  file: path=/opt/mindmaps/bin state=directory

- name: Removing default deployment directory
  file: path=/var/lib/tomcat8/webapps/ROOT state=absent
