---

- name: Installing OpenVPN
  apt: name=openvpn update_cache=no state=present

- name: Copying configuration (YOU STILL NEED TO KEY THE SERVER)
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf owner=root group=root mode=600

